#!/usr/bin/env python3
"""
generate_all_figures.py - Master Script for All Thesis Figures
==============================================================

PURPOSE:
Generate all figures used in the Golden Cage thesis from thesis_panel_v3.nc.
This is the SINGLE SOURCE OF TRUTH for figure generation.

FIGURE INVENTORY (from Thesis_Master.md):
------------------------------------------
| Figure | Name                              | Chapter | Generated By |
|--------|-----------------------------------|---------|--------------|
| 1      | The Funding-Growth Paradox        | Ch.1    | _gen_fig1_*  |
| 2      | Mediation Structure               | Ch.1    | _gen_fig2_*  |
| 3      | Strategic Breadth Trajectories    | Ch.2    | _gen_fig3_*  |
| 4      | The Golden Cage Mechanism         | Ch.2    | External     |
| 5      | The Mover Advantage               | Ch.4    | _gen_fig5_*  |
| 6      | Mover vs Stayer Success Rates     | Ch.4    | _gen_fig6_*  |
| 7      | Industry ρ(E,G) Correlations      | Ch.4    | _gen_fig7_*  |
| 8      | Mobility Survival                 | Ch.4    | _gen_fig8_*  |
| 9      | Temporal Robustness               | Ch.4    | _gen_fig9_*  |
| 10     | Sweet Spot                        | Ch.5    | _gen_fig10_* |
| 11     | Balanced Growth (Diagonal)        | Ch.5    | _gen_fig11_* |

OUTPUT DIRECTORY:
../figures/

CANONICAL VALUES (from .thesis_stats.json):
- N = 180,994
- Mover Advantage = 2.60× (18.1% vs 7.0%)
- ρ(E,G) = -0.196***
- ρ(E,R) = -0.087***

Author: Claude Code CLI
Date: 2026-01-14
Version: 1.0.0
"""

from __future__ import annotations

import json
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import xarray as xr
from scipy.stats import spearmanr, chi2_contingency

# ============================================================================
# CONFIGURATION
# ============================================================================

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    datefmt='%H:%M:%S'
)
log = logging.getLogger(__name__)

SCRIPT_DIR = Path(__file__).parent.resolve()
DATA_DIR = SCRIPT_DIR / 'data'
FIGURE_DIR = SCRIPT_DIR.parent / 'figures'
FIGURE_DIR.mkdir(parents=True, exist_ok=True)

# Color palette (grayscale for thesis)
COLORS = {
    'mover': '#2c3e50',      # Dark gray
    'stayer': '#bdc3c7',     # Light gray
    'positive': '#27ae60',   # Green (for positive correlations)
    'negative': '#c0392b',   # Red (for negative correlations)
    'neutral': '#7f8c8d',    # Medium gray
    'highlight': '#f39c12',  # Gold/amber for emphasis
}

# Plot style
plt.rcParams.update({
    'figure.dpi': 150,
    'font.size': 11,
    'font.family': 'DejaVu Sans',
    'axes.titleweight': 'bold',
    'axes.labelweight': 'bold',
    'savefig.bbox': 'tight',
    'savefig.facecolor': 'white',
    'savefig.dpi': 300,
})


# ============================================================================
# DATA LOADING
# ============================================================================

def load_data() -> pd.DataFrame:
    """Load thesis panel data."""
    path = DATA_DIR / 'thesis_panel_v3.nc'
    if not path.exists():
        raise FileNotFoundError(f"Data not found: {path}")

    ds = xr.open_dataset(path)
    df = ds.to_dataframe().reset_index()
    ds.close()

    log.info(f"Loaded {len(df):,} rows from {path.name}")
    return df


def load_canonical_stats() -> Dict:
    """Load canonical statistics from .thesis_stats.json."""
    repo_root = Path("/Users/hyunjimoon/tolzul/Front/On/love(cs)/strategic_ambiguity/empirics")
    stats_path = repo_root / '.thesis_stats.json'

    if stats_path.exists():
        with open(stats_path) as f:
            return json.load(f)
    return {}


# ============================================================================
# FIGURE 5: MOVER ADVANTAGE (Primary Figure)
# ============================================================================

def generate_fig5_mover_advantage(df: pd.DataFrame, save: bool = True) -> plt.Figure:
    """Generate Figure 5: The Mover Advantage bar chart.

    Shows:
    - Stayer success rate: 7.0%
    - Mover success rate: 18.1%
    - Mover Advantage: 2.60×

    Args:
        df: DataFrame with M and L columns
        save: Whether to save to file

    Returns:
        matplotlib Figure
    """
    log.info("Generating Figure 5: Mover Advantage")

    # Classify
    movers = df['M'] > 0
    stayers = df['M'] == 0

    # Calculate rates
    mover_success = df.loc[movers, 'L'].mean() * 100
    stayer_success = df.loc[stayers, 'L'].mean() * 100
    advantage = mover_success / stayer_success

    n_movers = movers.sum()
    n_stayers = stayers.sum()

    # Create figure
    fig, ax = plt.subplots(figsize=(8, 6))

    # Bar chart
    categories = ['Stayers\n(R = 0)', 'Movers\n(R > 0)']
    rates = [stayer_success, mover_success]
    n_values = [n_stayers, n_movers]
    colors = [COLORS['stayer'], COLORS['mover']]

    bars = ax.bar(categories, rates, color=colors, edgecolor='black', linewidth=1.5, width=0.6)

    # Value labels on bars
    for i, (bar, rate, n) in enumerate(zip(bars, rates, n_values)):
        # Rate on top
        ax.text(bar.get_x() + bar.get_width()/2, rate + 1,
                f'{rate:.1f}%', ha='center', fontsize=14, fontweight='bold')
        # N inside bar
        text_color = 'white' if i == 1 else COLORS['mover']
        ax.text(bar.get_x() + bar.get_width()/2, rate/2,
                f'n = {n:,}', ha='center', fontsize=10, color=text_color, fontweight='bold')

    # Advantage annotation
    mid_x = 0.5
    max_y = max(rates)

    ax.annotate('', xy=(1, mover_success), xytext=(0, stayer_success),
                arrowprops=dict(arrowstyle='->', color=COLORS['mover'], lw=2,
                              connectionstyle='arc3,rad=0.2'))

    ax.text(mid_x, max_y * 1.15, f'{advantage:.2f}×',
            ha='center', fontsize=20, fontweight='bold', color=COLORS['mover'],
            bbox=dict(boxstyle='round,pad=0.3', facecolor='white',
                     edgecolor=COLORS['mover'], linewidth=2))

    ax.text(mid_x, max_y * 1.02, 'Mover Advantage', ha='center', fontsize=11, style='italic')

    # Labels
    ax.set_ylabel('Success Rate (%)', fontsize=12)
    ax.set_title('Figure 5: The Mover Advantage', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max_y * 1.35)

    # Chi-square
    contingency = pd.crosstab(movers, df['L'])
    chi2, p_value, _, _ = chi2_contingency(contingency)
    ax.text(0.98, 0.02, f'χ² = {chi2:,.0f}***', transform=ax.transAxes,
            ha='right', fontsize=9, color='gray')

    # Clean up
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    fig.text(0.5, -0.02, f'N = {len(df):,} | Mover = R > 0 (any repositioning)',
             ha='center', fontsize=9, color='gray')

    plt.tight_layout()

    if save:
        output_path = FIGURE_DIR / 'Ch4_Fig1_mover_advantage.png'
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        log.info(f"Saved: {output_path}")

    return fig


# ============================================================================
# FIGURE 6: MOVER VS STAYER BY DIRECTION
# ============================================================================

def generate_fig6_growth_by_direction(df: pd.DataFrame, save: bool = True) -> plt.Figure:
    """Generate Figure 6: Mover vs Stayer Success by Direction.

    Shows success rates for:
    - Stayers (R = 0)
    - Zoom-in movers (ΔB < 0)
    - Zoom-out movers (ΔB > 0)
    """
    log.info("Generating Figure 6: Growth by Direction")

    # Classify by direction
    stayers = df['M'] == 0
    zoom_in = (df['M'] > 0) & (df['D'] < 0)
    zoom_out = (df['M'] > 0) & (df['D'] > 0)

    # Calculate rates
    stayer_rate = df.loc[stayers, 'L'].mean() * 100
    zoom_in_rate = df.loc[zoom_in, 'L'].mean() * 100
    zoom_out_rate = df.loc[zoom_out, 'L'].mean() * 100

    n_stayer = stayers.sum()
    n_zoom_in = zoom_in.sum()
    n_zoom_out = zoom_out.sum()

    # Create figure
    fig, ax = plt.subplots(figsize=(10, 6))

    categories = ['Stayers\n(R = 0)', 'Zoom-in\n(ΔB < 0)', 'Zoom-out\n(ΔB > 0)']
    rates = [stayer_rate, zoom_in_rate, zoom_out_rate]
    n_values = [n_stayer, n_zoom_in, n_zoom_out]
    colors = [COLORS['stayer'], COLORS['mover'], COLORS['mover']]

    bars = ax.bar(categories, rates, color=colors, edgecolor='black', linewidth=1.5, width=0.6)

    # Labels
    for bar, rate, n in zip(bars, rates, n_values):
        ax.text(bar.get_x() + bar.get_width()/2, rate + 0.8,
                f'{rate:.1f}%', ha='center', fontsize=12, fontweight='bold')
        ax.text(bar.get_x() + bar.get_width()/2, rate/2,
                f'n = {n:,}', ha='center', fontsize=9, color='white', fontweight='bold')

    ax.set_ylabel('Success Rate (%)', fontsize=12)
    ax.set_title('Figure 6: Success Rates by Strategic Direction', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max(rates) * 1.25)

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()

    if save:
        output_path = FIGURE_DIR / 'Ch4_Fig3_growth_by_direction.png'
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        log.info(f"Saved: {output_path}")

    return fig


# ============================================================================
# FIGURE 1: FUNDING-GROWTH PARADOX
# ============================================================================

def generate_fig1_capital_paradox(df: pd.DataFrame, save: bool = True) -> plt.Figure:
    """Generate Figure 1: The Funding-Growth Paradox scatter plot.

    Shows negative correlation between E (early funding) and G (growth).
    """
    log.info("Generating Figure 1: Capital Paradox")

    # Filter valid data
    valid = df[['E', 'G']].dropna()
    valid = valid[(valid['E'] > 0) & (valid['G'].notna())]

    # Log transform E
    log_E = np.log1p(valid['E'])

    # Compute correlation
    rho, p_value = spearmanr(log_E, valid['G'])

    # Create figure
    fig, ax = plt.subplots(figsize=(10, 7))

    # Scatter with transparency
    ax.scatter(log_E, valid['G'], alpha=0.3, s=20, c=COLORS['neutral'], edgecolors='none')

    # Regression line
    z = np.polyfit(log_E, valid['G'], 1)
    p = np.poly1d(z)
    x_line = np.linspace(log_E.min(), log_E.max(), 100)
    ax.plot(x_line, p(x_line), color=COLORS['negative'], linewidth=2, linestyle='--',
            label=f'ρ = {rho:.3f}***')

    ax.set_xlabel('Log(Early Funding + 1)', fontsize=12)
    ax.set_ylabel('Growth (G)', fontsize=12)
    ax.set_title('Figure 1: The Funding-Growth Paradox', fontsize=14, fontweight='bold')

    ax.legend(loc='upper right', fontsize=11)

    # Annotation box
    textstr = f'N = {len(valid):,}\nρ = {rho:.3f}\np < 0.001'
    props = dict(boxstyle='round', facecolor='white', alpha=0.8)
    ax.text(0.02, 0.98, textstr, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()

    if save:
        output_path = FIGURE_DIR / 'Ch1_Fig1_capital_paradox.png'
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        log.info(f"Saved: {output_path}")

    return fig


# ============================================================================
# FIGURE 7: INDUSTRY CORRELATIONS
# ============================================================================

def generate_fig7_industry_rho(save: bool = True) -> plt.Figure:
    """Generate Figure 7: Industry ρ(E,G) Correlations.

    Uses hardcoded values from Thesis_Master.md Table.
    """
    log.info("Generating Figure 7: Industry Correlations")

    # Data from thesis (Table in §4.4)
    industries = ['Quantum', 'Software', 'MedTech', 'Pharma', 'Hardware', 'Transportation']
    rho_values = [0.095, -0.001, -0.048, -0.067, -0.108, -0.101]
    significance = ['*', 'ns', '***', '***', '***', '***']

    # Sort by rho
    sorted_idx = np.argsort(rho_values)[::-1]
    industries = [industries[i] for i in sorted_idx]
    rho_values = [rho_values[i] for i in sorted_idx]
    significance = [significance[i] for i in sorted_idx]

    # Create figure
    fig, ax = plt.subplots(figsize=(10, 6))

    colors = [COLORS['positive'] if r > 0 else COLORS['negative'] for r in rho_values]

    bars = ax.barh(industries, rho_values, color=colors, edgecolor='black', linewidth=1)

    # Value labels
    for bar, rho, sig in zip(bars, rho_values, significance):
        x_offset = 0.01 if rho >= 0 else -0.01
        ha = 'left' if rho >= 0 else 'right'
        ax.text(rho + x_offset, bar.get_y() + bar.get_height()/2,
                f'{rho:+.3f}{sig}', va='center', ha=ha, fontsize=10, fontweight='bold')

    # Vertical line at 0
    ax.axvline(x=0, color='black', linewidth=1)

    ax.set_xlabel('ρ(E, G)', fontsize=12)
    ax.set_title('Figure 7: Industry ρ(E,G) — Where the Cage Bites', fontsize=14, fontweight='bold')

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()

    if save:
        output_path = FIGURE_DIR / 'Ch4_Fig2_industry_rho.png'
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        log.info(f"Saved: {output_path}")

    return fig


# ============================================================================
# MAIN
# ============================================================================

def generate_all_figures():
    """Generate all thesis figures."""
    log.info("="*70)
    log.info("GENERATING ALL THESIS FIGURES")
    log.info("="*70)

    # Load data
    df = load_data()

    # Generate figures
    figures = {}

    try:
        figures['fig5'] = generate_fig5_mover_advantage(df)
    except Exception as e:
        log.error(f"Fig 5 failed: {e}")

    try:
        figures['fig6'] = generate_fig6_growth_by_direction(df)
    except Exception as e:
        log.error(f"Fig 6 failed: {e}")

    try:
        figures['fig1'] = generate_fig1_capital_paradox(df)
    except Exception as e:
        log.error(f"Fig 1 failed: {e}")

    try:
        figures['fig7'] = generate_fig7_industry_rho()
    except Exception as e:
        log.error(f"Fig 7 failed: {e}")

    log.info("="*70)
    log.info(f"Generated {len(figures)} figures")
    log.info(f"Output: {FIGURE_DIR}")
    log.info("="*70)

    return figures


if __name__ == '__main__':
    generate_all_figures()
