#!/bin/bash
# Auto-stop the audit loop after 24 hours and ask about resuming

THESIS_DIR="/Users/hyunjimoon/tolzul/Front/On/love(cs)/strategic_ambiguity/empirics/src/scripts/paper_generation/papers_v7_sail"
REPO_ROOT="/Users/hyunjimoon/tolzul"

# Stop the audit loop
"$THESIS_DIR/code/thesis_audit_loop.sh" --unschedule

# Create GitHub issue asking about resuming
cd "$REPO_ROOT"
gh issue create \
    --title "⏰ Thesis Audit Loop Paused - Resume?" \
    --body "$(cat <<'EOF'
## Audit Loop Auto-Stopped

The 3-hour thesis audit loop has been automatically paused after 24 hours (submission crunch period ended).

### Audit Summary
Check recent PRs and issues labeled `audit` for all findings from the past 24 hours.

### Resume?

**To resume audits**, run:
```bash
cd strategic_ambiguity/empirics/src/scripts/paper_generation/papers_v7_sail/code

# Every 3 hours (crunch mode)
./thesis_audit_loop.sh --schedule

# Daily (maintenance mode)  
./thesis_audit_loop.sh --daily
```

**If submission is complete**, just close this issue - no action needed.

---
🤖 Auto-generated by thesis_audit_autostop.sh
EOF
)" \
    --label "audit,question"

# Remove the auto-stop plist (one-shot)
launchctl unload "$HOME/Library/LaunchAgents/com.thesis.audit.autostop.plist" 2>/dev/null || true
rm -f "$HOME/Library/LaunchAgents/com.thesis.audit.autostop.plist"

echo "Audit loop stopped. GitHub issue created asking about resuming."
